const englishJD = [
    {
        id: 0,
        title: 'Back-End Developer',
        label: 'Junior',
        label_class: 'badge badge-pill badge-primary',
        salary: '$1000-$2000',
        description: {
            main: [
                'We are looking for qualified members to accompany and develop solutions to work with us:',
            ],
            sub: [
                'Build and deploy a large and stable system.',
                'Collaborate with AI engineers to design and launch new features.',
                'Research and update new technologies towards the INNOVATE goal of the whole company.',
            ],
        },
        requirements: {
            main: [
                'At least one year of experience working with NestJs knowledge is an advantage.',
                'Have a good understanding of Typescript, NestJS syntax, and read NestJS code. Object Oriented Programming.',
                'Experience working with TypeORM (Postgres), Redis.',
                'Experience working with SocketIO, Apollo GraphQL, knowing about WebRTC is an advantage.',
                'Work proficiently with Git, Github',
            ],
            sub: [],
        },
        prefer: [
            'Have the ability to learn and research OpenSource.',
            'Good English to read technical documents.',
            'Have experience working with ESlint / Jest testing.',
            'Understand optimal processing Performance (High processing, Asynchronous), Security(encrypt/decrypt data).',
            'Experience in writing automated Test cases.',
        ],
        benefits: [
            'Young, dynamic, creative and comfortable working environment, performance evaluation twice/year, 13th month salary.',
            'Great opportunities to get self promotion and recognitions coming from member’s contributions',
            'Receive weekly training sessions on skill development, business knowledge, etc...',
            'Company trip twice / year, team building every month, tea-break every week.',
            'Full insurance coverage.',
        ],
        experience: '3-5 years',
        level: "Bachelor's Degree",
        schedule: 'Fulltime/Parttime',
    },
    // {
    //     id: 1,
    //     title: 'System Engineer',
    //     label: 'Senior',
    //     label_class: 'badge badge-pill badge-danger',
    //     salary: '$600-$900 (Negotiable)',
    //     description: {
    //         main: [],
    //         sub: [
    //             'Design infrastructures that ensure scablability, reliability, high availability, performance and security standards.',
    //             'Design and maintain procedures and checklists regarding monitoring and backup.',
    //             'Deploy modules for automated testing.',
    //             'Monitor services and coordinate with development/operations team to handle problems.',
    //             'Research and implement new technologies and develop tools to enhance productivity.',
    //             'Participate in developing network infrastructures.',
    //             'Setup servers by using automated tools.',
    //             'Participate in infrastructure tasks with Linux in projects.',
    //         ],
    //     },
    //     requirements: {
    //         main: [
    //             'Understanding of System Admin position, leaning towards SRE, DevOps and Cloud Engineer pathway',
    //             'Good understanding of computer hardware and networking',
    //             'Experienced in using Github and Github Action',
    //             'Good understanding of Docker, Kubernetes, Ansible and Terraform',
    //             'Sufficient English skills to read and understand documents',
    //             'Hardworking and self-learning capabilities',
    //             'Good to haves',
    //         ],
    //         sub: [
    //             'Research into OpenSource',
    //             'Understanding tools used in monitoring systems (fluentD, prometheus, grafa,...)',
    //             'Understanding of Python, Nodejs, nginx',
    //             'Possess Public Cloud certifications (AWS, GCP)',
    //             'Basic understanding of Database servers (SQL, NOSQL), cache (Redis), Networking and Routing',
    //             'Ability to deploy A.I solutions',
    //             'Experience with Scrum framework',
    //         ],
    //     },
    //     benefits: [
    //         'Young, dynamic, creative and comfortable working environment, performance evaluation twice/year, 13th month salary.',
    //         'Great opportunities to get self promotion and recognitions coming from member’s contributions.',
    //         'Receive weekly training sessions on skill development, business knowledge, etc...',
    //         'Company trip twice / year, team building every month, tea-break every week.',
    //         'Full insurance coverage.',
    //     ],
    //     experience: 'N/A',
    //     level: "Bachelor's Degree",
    //     schedule: 'Fulltime',
    // },
    // {
    //     id: 2,
    //     title: 'HR & Admin Executive',
    //     label: 'Middle',
    //     label_class: 'badge badge-pill badge-primary',
    //     salary: '$300-$500 (Negotiable)',
    //     description: {
    //         main: [],
    //         sub: [
    //             'Personnel management and recruitment',
    //             'Develop policies and regulations, as well as manage HR-related activities such as apprenticeship, probationary period, labor contract, salary, bonus, annual leave, personnel decision, labor contract, timekeeping, salary calculation, leave, and so on',
    //             'Keep track of and record monthly increases and decreases in social insurance, health insurance, and unemployment insurance.',
    //             "Keep track of and put the company's welfare policies into action (Holiday bonus policies, understanding ...)",
    //             'Severance payments are made, and contracts for employees to leave are canceled.',
    //             'Manage personnel records and Human Resources department decisions.',
    //             "Carry out the company's administrative tasks.",
    //             'Prepare bids, contracts, and acceptance documents.',
    //             'Keep and manage records: contracts, acceptance, liquidation, and so on.',
    //             'Prepare administrative documents and customer dispatches.',
    //             "Receiving phone calls and managing the Company's incoming and outgoing correspondence.",
    //             "Managing Company employees' working hours.",
    //             'Other administrative duties as assigned by the Board of Directors',
    //             'Events and company events are organized.',
    //             'Management of the office, facilities,...',
    //             'Receive official documents, documents sent to the company, and forward to the appropriate authorities for resolution.',
    //             'The main point of contact for sending official documents, papers, and documents out of the company.',
    //             "Keep track of the company's expenses for internal accounts, receivables, and payables.",
    //             'Examine all official documents, contracts, and legal documents.',
    //         ],
    //     },
    //     requirements: {
    //         main: [
    //             'Fourth-year students (with the ability to work full-time) or graduates from a university majoring in Human Resource Management, Business Administration, or a related field are encouraged to apply.',
    //             'Office proficiency.',
    //             'Have strong communication, presentation, and problem-solving abilities.',
    //             'Have a progressive mindset, eager to learn, think big, and do big things.',
    //             'As the person in charge of the job, you must complete the request on time.',
    //         ],
    //         sub: [
    //             'Candidates with a legal background will be given preference.',
    //             'I used to be a team leader and have experience in leadership, human resources, and so on.',
    //             'I am fascinated by research, discovery, and innovation.',
    //             'Knowledge of economics, finance, and business management processes and operations.',
    //             'Good English skills are required to read and comprehend specialized documents and terms.',
    //         ],
    //     },
    //     benefits: [
    //         'Young, dynamic, creative and comfortable working environment, performance evaluation twice/year, 13th month salary.',
    //         'Great opportunities to get self promotion and recognitions coming from member’s contributions.',
    //         'Receive weekly training sessions on skill development, business knowledge, etc...',
    //         'Company trip twice / year, team building every month, tea-break every week.',
    //         'Full insurance coverage.',
    //     ],
    //     experience: 'N/A',
    //     level: "Bachelor's Degree",
    //     schedule: 'Fulltime',
    // },
    {
        id: 3,
        title: 'Front-End Developer',
        label: 'Junior',
        label_class: 'badge badge-pill badge-primary',
        salary: '$800-$1200',
        description: {
            main: [
                'We are looking for qualified members to accompany and develop solutions, with the scope of work:',
            ],
            sub: [
                'Build camera A.I and management system with ReactJS, NextJS ',
                'Write reusable web components with documentation, unit test and great UI',
                'Enhance and refactor your code on a daily basis',
                'Participate in team discussion and code reviews',
            ],
        },
        requirements: {
            main: [
                'Experience using React.JS on at least 1 production project',
                'Experience with state management (React context & React redux)',
                'Experience with designing and interacting with GraphQL; API authentication/ authorization schemes',
                'Proficient understanding of Github',
                'Follow best practice conventions (eslint, comment, oop) and project structure',
            ],
            sub: [],
        },
        benefits: [
            'Young, dynamic, creative and comfortable working environment, performance evaluation twice/year, 13th month salary.',
            'Great opportunities to get self promotion and recognitions coming from member’s contributions.',
            'Receive weekly training sessions on skill development, business knowledge, etc...',
            'Company trip twice / year, team building every month, tea-break every week.',
            'Full insurance coverage.',
        ],
        prefer: [
            'Experience with troubleshooting browser rendering bottleneck with web DOM',
            'SEO Integration',
            'Understanding in Typescript',
            'Experience with in Eslint/Mocha/Jest testing',
            'Experience with scrum workflow',
            'Having working experience in design tools such as: figma, wireframe.cc, etc',
            'Upper intermediate English skills that can be fluent in reading and communication',
            'Good coding skill',
        ],
        experience: '3-5 years',
        level: "Bachelor's Degree",
        schedule: 'Fulltime/Parttime',
    },
    {
        id: 4,
        title: 'Full-Stack Developer',
        label: 'Junior',
        label_class: 'badge badge-pill badge-primary',
        salary: '$1000-$2000',
        description: {
            main: [],
            sub: [
                'Build and Deploy large and scalable system.',
                'Design overall architecture of the web application.',
                'Collaborate with the engineering team (AI engineers) to design and launch new features.',
                'Research and explore new technologies to present findings to development team.',
                'Write reports and prepare documents.',
            ],
        },
        requirements: {
            main: [
                '>2 year experience in Javascript ( VueJS / ReactJS ), NodeJS ( Express / SocketIO,…).',
                'Experienced with RESTful API, GraphQL',
                'Experience in SQL and noSQL databases (for example MySQL and MongoDB.',
                'Knowledge of code versioning tools like GitHub/GitLab.',
                'Proactive/ Self Study abilities / Adaptability / Team work spirit.',
                'Good to haves:',
            ],
            sub: [],
        },
        prefer: [
            'Ability to learn and research OpenSource',
            'Sufficient English proficiency to read technical documents',
            'Typescript experience',
            'e2e testing experience',
        ],
        benefits: [
            'Young, dynamic, creative and comfortable working environment, performance evaluation twice/year, 13th month salary.',
            'Great opportunities to get self promotion and recognitions coming from member’s contributions.',
            'Receive weekly training sessions on skill development, business knowledge, etc...',
            'Company trip twice / year, team building every month, tea-break every week.',
            'Full insurance coverage.',
        ],
        experience: 'Minimum 2 years',
        level: "Bachelor's Degree",
        schedule: 'Fulltime/Parttime',
    },
    {
        id: 5,
        title: 'Back-End Developer',
        label: 'Fresher',
        label_class: 'badge badge-pill badge-success',
        salary: '$500-$1000',
        description: {
            main: [
                'We are looking for qualified members to accompany and develop solutions to work with us:',
            ],
            sub: [
                'Build and deploy a large and stable system.',
                'Collaborate with AI engineers to design and launch new features.',
                'Research and update new technologies towards the INNOVATE goal of the whole company.',
            ],
        },
        requirements: {
            main: [
                'At least one year of experience working with NestJs knowledge is an advantage.',
                'Have a good understanding of Typescript, NestJS syntax, and read NestJS code. Object Oriented Programming.',
                'Experience working with TypeORM (Postgres), Redis.',
                'Experience working with SocketIO, Apollo GraphQL, knowing about WebRTC is an advantage.',
                'Work proficiently with Git, Github',
            ],
            sub: [],
        },
        prefer: [
            'Have the ability to learn and research OpenSource.',
            'Good English to read technical documents.',
            'Have experience working with ESlint / Jest testing.',
            'Understand optimal processing Performance (High processing, Asynchronous), Security(encrypt/decrypt data).',
            'Experience in writing automated Test cases.',
        ],
        benefits: [
            'Young, dynamic, creative and comfortable working environment, performance evaluation twice/year, 13th month salary.',
            'Great opportunities to get self promotion and recognitions coming from member’s contributions',
            'Receive weekly training sessions on skill development, business knowledge, etc...',
            'Company trip twice / year, team building every month, tea-break every week.',
            'Full insurance coverage.',
        ],
        experience: 'N/A',
        level: "Bachelor's Degree",
        schedule: 'Fulltime/Parttime',
    },
    {
        id: 6,
        title: 'Front-End Developer',
        label: 'Fresher',
        label_class: 'badge badge-pill badge-success',
        salary: '$500-$1000',
        description: {
            main: [
                'We are looking for qualified members to accompany and develop solutions, with the scope of work:',
            ],
            sub: [
                'Build camera A.I and management system with ReactJS, NextJS ',
                'Write reusable web components with documentation, unit test and great UI',
                'Enhance and refactor your code on a daily basis',
                'Participate in team discussion and code reviews',
            ],
        },
        requirements: {
            main: [
                'Experience using React.JS on at least 1 production project',
                'Experience with state management (React context & React redux)',
                'Experience with designing and interacting with GraphQL; API authentication/ authorization schemes',
                'Proficient understanding of Github',
                'Follow best practice conventions (eslint, comment, oop) and project structure',
            ],
            sub: [],
        },
        benefits: [
            'Young, dynamic, creative and comfortable working environment, performance evaluation twice/year, 13th month salary.',
            'Great opportunities to get self promotion and recognitions coming from member’s contributions.',
            'Receive weekly training sessions on skill development, business knowledge, etc...',
            'Company trip twice / year, team building every month, tea-break every week.',
            'Full insurance coverage.',
        ],
        prefer: [
            'Experience with troubleshooting browser rendering bottleneck with web DOM',
            'SEO Integration',
            'Understanding in Typescript',
            'Experience with in Eslint/Mocha/Jest testing',
            'Experience with scrum workflow',
            'Having working experience in design tools such as: figma, wireframe.cc, etc',
            'Upper intermediate English skills that can be fluent in reading and communication',
            'Good coding skill',
        ],
        experience: 'N/A',
        level: "Bachelor's Degree",
        schedule: 'Fulltime/Parttime',
    },
]

export default englishJD
