const vietnameseJD = [
    {
        id: 0,
        title: 'Back-End Developer',
        label: 'Junior',
        label_class: 'badge badge-pill badge-primary',
        salary: '$1000-$2000',
        description: {
            main: [
                'Chúng tôi đang tìm kiếm những thành viên có đủ năng lực để đồng hành và phát triển các giải pháp, với phạm vi công việc như sau:',
            ],
            sub: [
                'Xây dựng và triển khai các hệ thống có quy mô lớn, ổn định.',
                'Cộng tác với các kỹ sư AI để thiết kế và để khởi chạy các tính năng mới.',
                'Nghiên cứu và cập nhật các công nghệ mới, hướng tới mục tiêu ĐỔI MỚI của toàn công ty.',
            ],
        },
        requirements: {
            main: [
                'Có ít nhất 01 năm kinh nghiệm làm việc với NestJs là một lợi thế',
                'Có hiểu biết tốt về Typescript, NestJS syntax, and read NestJS code. Lập trình hướng đối tượng.',
                'Có kinh nghiệm làm việc với TypeORM (Postgres), Redis.',
                'Có kinh nghiệm làm việc với SocketIO, Apollo GraphQL, biết về WebRTC là một lợi thế.',
                'Làm việc thành thạo với Git, Github',
            ],
            sub: [],
        },
        prefer: [
            'Có khả năng học và nghiên cứu OpenSource',
            'Khả năng Tiếng Anh tốt để đọc tài liệu kỹ thuật.',
            'Có kinh nghiệm làm việc với ESlint / Jest testing.',
            'Hiểu rõ về Hiệu suất xử lý tối ưu (Xử lý cao, Không đồng bộ), Bảo mật (mã hóa / giải mã dữ liệu).',
            'Có kinh nghiệm viết test cases tự động.',
        ],
        benefits: [
            'Môi trường làm việc trẻ trung, năng động, sáng tạo, thoải mái, đánh giá thành tích 2 lần / năm, lương tháng 13.',
            'Có cơ hội được tự phát triển và ghi nhận những đóng góp từ các thành viên.',
            'Tham gia các buổi đào tạo hàng tuần về phát triển kỹ năng, kiến thức kinh doanh, v.v.',
            'Du lịch công ty 2 lần / năm, team building hàng tháng, tea-break hàng tuần.',
            'Bảo hiểm đóng theo vùng.',
        ],
        experience: '3-5 năm',
        level: 'Bằng cử nhân',
        schedule: 'Fulltime/Parttime',
    },
    // {
    //     id: 1,
    //     title: 'System Engineer',
    //     label: 'Senior',
    //     label_class: 'badge badge-pill badge-danger',
    //     salary: '$600-$900 (Negotiable)',
    //     description: {
    //         main: [],
    //         sub: [
    //             'Design infrastructures that ensure scablability, reliability, high availability, performance and security standards.',
    //             'Design and maintain procedures and checklists regarding monitoring and backup.',
    //             'Deploy modules for automated testing.',
    //             'Monitor services and coordinate with development/operations team to handle problems.',
    //             'Research and implement new technologies and develop tools to enhance productivity.',
    //             'Participate in developing network infrastructures.',
    //             'Setup servers by using automated tools.',
    //             'Participate in infrastructure tasks with Linux in projects.',
    //         ],
    //     },
    //     requirements: {
    //         main: [
    //             'Understanding of System Admin position, leaning towards SRE, DevOps and Cloud Engineer pathway',
    //             'Good understanding of computer hardware and networking',
    //             'Experienced in using Github and Github Action',
    //             'Good understanding of Docker, Kubernetes, Ansible and Terraform',
    //             'Sufficient English skills to read and understand documents',
    //             'Hardworking and self-learning capabilities',
    //             'Good to haves',
    //         ],
    //         sub: [
    //             'Research into OpenSource',
    //             'Understanding tools used in monitoring systems (fluentD, prometheus, grafa,...)',
    //             'Understanding of Python, Nodejs, nginx',
    //             'Possess Public Cloud certifications (AWS, GCP)',
    //             'Basic understanding of Database servers (SQL, NOSQL), cache (Redis), Networking and Routing',
    //             'Ability to deploy A.I solutions',
    //             'Experience with Scrum framework',
    //         ],
    //     },
    //     benefits: [
    //         'Young, dynamic, creative and comfortable working environment, performance evaluation twice/year, 13th month salary.',
    //         'Great opportunities to get self promotion and recognitions coming from member’s contributions.',
    //         'Receive weekly training sessions on skill development, business knowledge, etc...',
    //         'Company trip twice / year, team building every month, tea-break every week.',
    //         'Full insurance coverage.',
    //     ],
    //     experience: 'N/A',
    //     level: "Bachelor's Degree",
    //     schedule: 'Fulltime',
    // },
    // {
    //     id: 2,
    //     title: 'HR & Admin Executive',
    //     label: 'Middle',
    //     label_class: 'badge badge-pill badge-primary',
    //     salary: '$300-$500 (Negotiable)',
    //     description: {
    //         main: [],
    //         sub: [
    //             'Personnel management and recruitment',
    //             'Develop policies and regulations, as well as manage HR-related activities such as apprenticeship, probationary period, labor contract, salary, bonus, annual leave, personnel decision, labor contract, timekeeping, salary calculation, leave, and so on',
    //             'Keep track of and record monthly increases and decreases in social insurance, health insurance, and unemployment insurance.',
    //             "Keep track of and put the company's welfare policies into action (Holiday bonus policies, understanding ...)",
    //             'Severance payments are made, and contracts for employees to leave are canceled.',
    //             'Manage personnel records and Human Resources department decisions.',
    //             "Carry out the company's administrative tasks.",
    //             'Prepare bids, contracts, and acceptance documents.',
    //             'Keep and manage records: contracts, acceptance, liquidation, and so on.',
    //             'Prepare administrative documents and customer dispatches.',
    //             "Receiving phone calls and managing the Company's incoming and outgoing correspondence.",
    //             "Managing Company employees' working hours.",
    //             'Other administrative duties as assigned by the Board of Directors',
    //             'Events and company events are organized.',
    //             'Management of the office, facilities,...',
    //             'Receive official documents, documents sent to the company, and forward to the appropriate authorities for resolution.',
    //             'The main point of contact for sending official documents, papers, and documents out of the company.',
    //             "Keep track of the company's expenses for internal accounts, receivables, and payables.",
    //             'Examine all official documents, contracts, and legal documents.',
    //         ],
    //     },
    //     requirements: {
    //         main: [
    //             'Fourth-year students (with the ability to work full-time) or graduates from a university majoring in Human Resource Management, Business Administration, or a related field are encouraged to apply.',
    //             'Office proficiency.',
    //             'Have strong communication, presentation, and problem-solving abilities.',
    //             'Have a progressive mindset, eager to learn, think big, and do big things.',
    //             'As the person in charge of the job, you must complete the request on time.',
    //         ],
    //         sub: [
    //             'Candidates with a legal background will be given preference.',
    //             'I used to be a team leader and have experience in leadership, human resources, and so on.',
    //             'I am fascinated by research, discovery, and innovation.',
    //             'Knowledge of economics, finance, and business management processes and operations.',
    //             'Good English skills are required to read and comprehend specialized documents and terms.',
    //         ],
    //     },
    //     benefits: [
    //         'Young, dynamic, creative and comfortable working environment, performance evaluation twice/year, 13th month salary.',
    //         'Great opportunities to get self promotion and recognitions coming from member’s contributions.',
    //         'Receive weekly training sessions on skill development, business knowledge, etc...',
    //         'Company trip twice / year, team building every month, tea-break every week.',
    //         'Full insurance coverage.',
    //     ],
    //     experience: 'N/A',
    //     level: "Bachelor's Degree",
    //     schedule: 'Fulltime',
    // },
    {
        id: 3,
        title: 'Front-End Developer',
        label: 'Junior',
        label_class: 'badge badge-pill badge-primary',
        salary: '$800-$1200',
        description: {
            main: [
                'Chúng tôi đang tìm kiếm những thành viên có đủ năng lực để đồng hành và phát triển các giải pháp, với phạm vi công việc như sau:',
            ],
            sub: [
                'Xây dựng camera AI và hệ thống quản lý bằng ReactJS, NextJS.',
                'Viết các thành phần web có thể tái sử dụng, bao gồm tài liệu phù hợp, kiểm  thử đơn vị và UI tốt.',
                'Nâng cao và refactor code  hàng ngày.',
                'Tham gia thảo luận nhóm và đánh giá code.',
            ],
        },
        requirements: {
            main: [
                'Có kinh nghiệm sử dụng React.js trên ít nhất 1 dự án sản phẩm.',
                'Có kinh nghiệm với  quản lý trạng thái (React context & React redux)',
                'Có kinh nghiệm thiết kế và  thao tác với GraphQL; Cơ chế xác thực / ủy quyền API',
                'Hiểu biết và thành thạo về Git',
                'Tuân theo các quy ước về phương pháp hay nhất (eslint, comment, oop) và cấu trúc dự án',
            ],
            sub: [],
        },
        prefer: [
            'Có kinh nghiệm khắc phục sự cố tắc nghẽn kết xuất trình duyệt với Web DOM',
            'Tích hợp SEO',
            'Hiểu Typescript',
            'Có kinh nghiệm với Eslint/Mocha/Jest testing',
            'Có kinh nghiệm với quy trình làm việc Scrum',
            'Có kinh nghiệm trong việc thiết kế các công cụ: figma, wireframe.cc, etc',
            'Kỹ năng tiếng Anh trên trung cấp có thể thành thạo trong việc đọc và giao tiếp',
            'Có kỹ năng code là một lợi thế',
        ],
        benefits: [
            'Môi trường làm việc trẻ trung, năng động, sáng tạo, thoải mái, đánh giá thành tích 2 lần / năm, lương tháng 13.',
            'Có cơ hội được tự phát triển và ghi nhận những đóng góp từ các thành viên.',
            'Tham gia các buổi đào tạo hàng tuần về phát triển kỹ năng, kiến thức kinh doanh, v.v.',
            'Du lịch công ty 2 lần / năm, team building hàng tháng, tea-break hàng tuần.',
            'Bảo hiểm đóng theo vùng.',
        ],
        experience: '3-5 năm',
        level: 'Bằng cử nhân',
        schedule: 'Fulltime/Parttime',
    },
    {
        id: 4,
        title: 'Full-Stack Developer',
        label: 'Junior',
        label_class: 'badge badge-pill badge-primary',
        salary: '$800-$1200',
        description: {
            main: [],
            sub: [
                'Xây dựng và triển khai các hệ thống có quy mô lớn và có khả năng mở rộng.',
                'Thiết kế kiến trúc tổng thể của ứng dụng web.',
                'Cộng tác với nhóm kỹ sư (kỹ sư AI) để thiết kế và khởi chạy các tính năng mới.',
                'Nghiên cứu và khám phá các công nghệ mới để trình bày những phát hiện cho nhóm phát triển.',
                'Viết báo cáo và chuẩn bị tài liệu.',
            ],
        },
        requirements: {
            main: [
                '> 2 năm kinh nghiệm về JavaScript (Vue.js / React.js), Node.js(Express / Socket.IO,…).',
                'Có kinh nghiệm với RESTful API, GraphQL',
                'Có kinh nghiệm về cơ sở dữ liệu SQL và NoSQL (ví dụ: MySQL và MongoDB).',
                'Kiến thức về các  hệ thống quản lý phiên bản code như GitHub / GitLab.',
                'Khả năng chủ động / Tự học / Khả năng thích ứng / Tinh thần làm việc nhóm.',
                'Good to haves:',
            ],
            sub: [],
        },
        prefer: [
            'Khả năng học hỏi và nghiên cứu OpenSource',
            'Trình độ tiếng Anh đủ để đọc các tài liệu kỹ thuật',
            'Có kiến thức về Typescript',
            'Kinh nghiệm thử nghiệm e2e',
        ],
        benefits: [
            'Young, dynamic, creative and comfortable working environment, performance evaluation twice/year, 13th month salary.',
            'Great opportunities to get self promotion and recognitions coming from member’s contributions.',
            'Receive weekly training sessions on skill development, business knowledge, etc...',
            'Company trip twice / year, team building every month, tea-break every week.',
            'Full insurance coverage.',
        ],
        benefits: [
            'Môi trường làm việc trẻ trung, năng động, sáng tạo, thoải mái, đánh giá thành tích 2 lần / năm, lương tháng 13.',
            'Có cơ hội được tự phát triển và ghi nhận những đóng góp từ các thành viên.',
            'Tham gia các buổi đào tạo hàng tuần về phát triển kỹ năng, kiến thức kinh doanh, v.v.',
            'Du lịch công ty 2 lần / năm, team building hàng tháng, tea-break hàng tuần.',
            'Bảo hiểm đóng theo vùng.',
        ],
        experience: 'Ít nhất 2 năm',
        level: 'Bằng cử nhân',
        schedule: 'Fulltime/Parttime',
    },
    {
        id: 5,
        title: 'Back-End Developer',
        label: 'Junior',
        label_class: 'badge badge-pill badge-success',
        salary: '$1000-$2000',
        description: {
            main: [
                'Chúng tôi đang tìm kiếm những thành viên có đủ năng lực để đồng hành và phát triển các giải pháp, với phạm vi công việc như sau:',
            ],
            sub: [
                'Xây dựng và triển khai các hệ thống có quy mô lớn, ổn định.',
                'Cộng tác với các kỹ sư AI để thiết kế và để khởi chạy các tính năng mới.',
                'Nghiên cứu và cập nhật các công nghệ mới, hướng tới mục tiêu ĐỔI MỚI của toàn công ty.',
            ],
        },
        requirements: {
            main: [
                'Có ít nhất 01 năm kinh nghiệm làm việc với NestJs là một lợi thế',
                'Có hiểu biết tốt về Typescript, NestJS syntax, and read NestJS code. Lập trình hướng đối tượng.',
                'Có kinh nghiệm làm việc với TypeORM (Postgres), Redis.',
                'Có kinh nghiệm làm việc với SocketIO, Apollo GraphQL, biết về WebRTC là một lợi thế.',
                'Làm việc thành thạo với Git, Github',
            ],
            sub: [],
        },
        prefer: [
            'Có khả năng học và nghiên cứu OpenSource',
            'Khả năng Tiếng Anh tốt để đọc tài liệu kỹ thuật.',
            'Có kinh nghiệm làm việc với ESlint / Jest testing.',
            'Hiểu rõ về Hiệu suất xử lý tối ưu (Xử lý cao, Không đồng bộ), Bảo mật (mã hóa / giải mã dữ liệu).',
            'Có kinh nghiệm viết test cases tự động.',
        ],
        benefits: [
            'Môi trường làm việc trẻ trung, năng động, sáng tạo, thoải mái, đánh giá thành tích 2 lần / năm, lương tháng 13.',
            'Có cơ hội được tự phát triển và ghi nhận những đóng góp từ các thành viên.',
            'Tham gia các buổi đào tạo hàng tuần về phát triển kỹ năng, kiến thức kinh doanh, v.v.',
            'Du lịch công ty 2 lần / năm, team building hàng tháng, tea-break hàng tuần.',
            'Bảo hiểm đóng theo vùng.',
        ],
        experience: 'N/A',
        level: 'Bằng cử nhân',
        schedule: 'Fulltime/Parttime',
    },
    {
        id: 6,
        title: 'Front-End Developer',
        label: 'Fresher',
        label_class: 'badge badge-pill badge-success',
        salary: '$500-$1000',
        description: {
            main: [
                'Chúng tôi đang tìm kiếm những thành viên có đủ năng lực để đồng hành và phát triển các giải pháp, với phạm vi công việc như sau:',
            ],
            sub: [
                'Xây dựng camera AI và hệ thống quản lý bằng ReactJS, NextJS.',
                'Viết các thành phần web có thể tái sử dụng, bao gồm tài liệu phù hợp, kiểm  thử đơn vị và UI tốt.',
                'Nâng cao và refactor code  hàng ngày.',
                'Tham gia thảo luận nhóm và đánh giá code.',
            ],
        },
        requirements: {
            main: [
                'Có kinh nghiệm sử dụng React.js trên ít nhất 1 dự án sản phẩm.',
                'Có kinh nghiệm với  quản lý trạng thái (React context & React redux)',
                'Có kinh nghiệm thiết kế và  thao tác với GraphQL; Cơ chế xác thực / ủy quyền API',
                'Hiểu biết và thành thạo về Git',
                'Tuân theo các quy ước về phương pháp hay nhất (eslint, comment, oop) và cấu trúc dự án',
            ],
            sub: [],
        },
        prefer: [
            'Có kinh nghiệm khắc phục sự cố tắc nghẽn kết xuất trình duyệt với Web DOM',
            'Tích hợp SEO',
            'Hiểu Typescript',
            'Có kinh nghiệm với Eslint/Mocha/Jest testing',
            'Có kinh nghiệm với quy trình làm việc Scrum',
            'Có kinh nghiệm trong việc thiết kế các công cụ: figma, wireframe.cc, etc',
            'Kỹ năng tiếng Anh trên trung cấp có thể thành thạo trong việc đọc và giao tiếp',
            'Có kỹ năng code là một lợi thế',
        ],
        benefits: [
            'Môi trường làm việc trẻ trung, năng động, sáng tạo, thoải mái, đánh giá thành tích 2 lần / năm, lương tháng 13.',
            'Có cơ hội được tự phát triển và ghi nhận những đóng góp từ các thành viên.',
            'Tham gia các buổi đào tạo hàng tuần về phát triển kỹ năng, kiến thức kinh doanh, v.v.',
            'Du lịch công ty 2 lần / năm, team building hàng tháng, tea-break hàng tuần.',
            'Bảo hiểm đóng theo vùng.',
        ],
        experience: 'N/A',
        level: 'Bằng cử nhân',
        schedule: 'Fulltime/Parttime',
    },
]

export default vietnameseJD
